package net.nuggetmc.tplus.compat.bukkit.enchantments;
public enum Enchantment {
    KNOCKBACK, PIERCING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, FIRE_ASPECT, LOOTING, SWEEPING_EDGE,
    UNBREAKING, MENDING, PROTECTION, BLAST_PROTECTION, FEATHER_FALLING, PROJECTILE_PROTECTION,
    RESPIRATION, AQUA_AFFINITY, THORNS, DEPTH_STRIDER, FROST_WALKER, SOUL_SPEED, SWIFT_SNEAK,
    POWER, PUNCH, FLAME, INFINITY, MULTISHOT, QUICK_CHARGE, LOYALTY, IMPALING, RIPTIDE, CHANNELING,
    WIND_BURST, DENSITY, BREACH, EFFICIENCY
}
