package net.nuggetmc.tplus.compat.bukkit.potion;
public enum PotionType { HEALING, STRONG_HEALING, HARMING, STRONG_HARMING, POISON, STRONG_POISON, LONG_POISON, WEAKNESS, SLOW_FALLING, SWIFTNESS, STRONG_SWIFTNESS, LONG_SWIFTNESS, SLOWNESS, STRONG_SLOWNESS, LONG_SLOWNESS, STRENGTH, STRONG_STRENGTH, FIRE_RESISTANCE, LONG_FIRE_RESISTANCE, REGENERATION, LONG_REGENERATION }
