package net.nuggetmc.tplus.compat.bukkit;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;

/** Internal name bridge. Public APIs use vanilla Item/Block/ResourceLocation types. */
public enum Material {
    AIR,ALLIUM,ARROW,AZALEA,AZURE_BLUET,BARRIER,BAMBOO,BEACON,BEDROCK,BEETROOT_SEEDS,BELL,BIG_DRIPLEAF,BLUE_ORCHID,BOOK,BOW,BRICKS,BREWING_STAND,BROWN_MUSHROOM,BUCKET,CACTUS,CAKE,CAMPFIRE,CARROTS,CAULDRON,CAVE_AIR,CAVE_VINES,CAVE_VINES_PLANT,CHAIN,CHAINMAIL_BOOTS,CHAINMAIL_CHESTPLATE,CHAINMAIL_HELMET,CHAINMAIL_LEGGINGS,CHAIN_COMMAND_BLOCK,CHEST,CHORUS_FLOWER,CHORUS_PLANT,COBBLED_DEEPSLATE,COBBLESTONE,COBWEB,COCOA,COMMAND_BLOCK,COMPARATOR,COMPASS,COMPOSTER,CONDUIT,CORNFLOWER,CRIMSON_FUNGUS,CRIMSON_ROOTS,CRYING_OBSIDIAN,DANDELION,DAYLIGHT_DETECTOR,DEAD_BUSH,DIAMOND_AXE,DIAMOND_BOOTS,DIAMOND_CHESTPLATE,DIAMOND_HELMET,DIAMOND_LEGGINGS,DIAMOND_SWORD,DIRT,DRAGON_EGG,ELYTRA,ENCHANTED_BOOK,ENCHANTED_GOLDEN_APPLE,ENCHANTING_TABLE,ENDER_CHEST,ENDER_PEARL,END_CRYSTAL,END_GATEWAY,END_PORTAL,END_PORTAL_FRAME,END_ROD,EXPERIENCE_BOTTLE,FEATHER,FERN,FARMLAND,FIRE,FIREWORK_ROCKET,FIRE_CHARGE,FLINT_AND_STEEL,FLOWERING_AZALEA,FLOWER_POT,GLASS_PANE,GLOWSTONE,GOLDEN_APPLE,GOLDEN_AXE,GOLDEN_BOOTS,GOLDEN_CHESTPLATE,GOLDEN_HELMET,GOLDEN_LEGGINGS,GOLDEN_SWORD,GRASS_BLOCK,GRAY_DYE,GRAY_STAINED_GLASS_PANE,GLOW_LICHEN,GRINDSTONE,HANGING_ROOTS,HONEY_BLOCK,HOPPER,IRON_AXE,IRON_BARS,IRON_BOOTS,IRON_CHESTPLATE,IRON_HELMET,IRON_LEGGINGS,IRON_PICKAXE,IRON_SHOVEL,IRON_SWORD,KELP,KELP_PLANT,LADDER,LANTERN,LARGE_AMETHYST_BUD,LARGE_FERN,LAVA,LAVA_BUCKET,LEATHER_BOOTS,LEATHER_CHESTPLATE,LEATHER_HELMET,LEATHER_LEGGINGS,LECTERN,LIGHTNING_ROD,LILAC,LILY_OF_THE_VALLEY,LILY_PAD,LIME_DYE,LIME_WOOL,LINGERING_POTION,MACE,MAGMA_BLOCK,MANGROVE_ROOTS,MAP,MEDIUM_AMETHYST_BUD,MELON_STEM,NETHERITE_AXE,NETHERITE_BOOTS,NETHERITE_CHESTPLATE,NETHERITE_HELMET,NETHERITE_LEGGINGS,NETHERITE_SWORD,NETHER_PORTAL,NETHER_WART,OAK_PLANKS,OBSERVER,OBSIDIAN,ORANGE_TULIP,OXEYE_DAISY,PAPER,PEONY,PINK_TULIP,PITCHER_PLANT,PISTON_HEAD,PLAYER_HEAD,POINTED_DRIPSTONE,POPPY,POTION,POTATOES,POWDER_SNOW,PUMPKIN_STEM,REDSTONE,REDSTONE_TORCH,REDSTONE_WALL_TORCH,REDSTONE_WIRE,RED_DYE,RED_MUSHROOM,RED_TULIP,RED_WOOL,REPEATER,REPEATING_COMMAND_BLOCK,RESPAWN_ANCHOR,ROSE_BUSH,SCAFFOLDING,SCULK_SENSOR,SCULK_SHRIEKER,SCULK_VEIN,SEAGRASS,SEA_PICKLE,SHIELD,SHORT_GRASS,SHULKER_BOX,SLIME_BLOCK,SMALL_AMETHYST_BUD,SNOW,SOUL_CAMPFIRE,SOUL_FIRE,SOUL_LANTERN,SOUL_TORCH,SOUL_WALL_TORCH,SPECTRAL_ARROW,SPLASH_POTION,SPORE_BLOSSOM,SPYGLASS,STONE,STONECUTTER,STONE_AXE,STONE_SWORD,STRING,STRUCTURE_BLOCK,SUGAR_CANE,SUNFLOWER,SWEET_BERRY_BUSH,TALL_GRASS,TALL_SEAGRASS,TIPPED_ARROW,TNT,TORCH,TORCHFLOWER,TOTEM_OF_UNDYING,TRAPPED_CHEST,TRIDENT,TRIPWIRE,TRIPWIRE_HOOK,TWISTING_VINES,TWISTING_VINES_PLANT,TURTLE_EGG,VINE,VOID_AIR,WALL_TORCH,WARPED_FUNGUS,WARPED_ROOTS,WATER,WATER_BUCKET,WEEPING_VINES,WEEPING_VINES_PLANT,WHEAT_SEEDS,WHITE_TULIP,WIND_CHARGE,WITHER_ROSE,WOODEN_AXE,WOODEN_SWORD,WRITABLE_BOOK,ZOMBIE_HEAD,CROSSBOW;

    /** Compatibility metadata used by the legacy movement taxonomy. */
    public Class<?> data = net.nuggetmc.tplus.compat.bukkit.block.data.BlockData.class;

    public static Material matchMaterial(String name) {
        if (name == null) return null;
        try { return valueOf(name.toUpperCase(java.util.Locale.ROOT)); } catch (IllegalArgumentException ignored) { return null; }
    }
    public boolean isAir() { return this == AIR || this == CAVE_AIR || this == VOID_AIR; }
    public boolean isBlock() { return BuiltInRegistries.BLOCK.containsKey(ResourceLocation.withDefaultNamespace(name().toLowerCase(java.util.Locale.ROOT))); }
    public boolean isItem() { return item() != null; }
    public boolean isSolid() { return switch (this) { case AIR,CAVE_AIR,VOID_AIR,WATER,LAVA,FIRE,SOUL_FIRE -> false; default -> isBlock(); }; }
    public boolean isEdible() { return this == GOLDEN_APPLE || this == ENCHANTED_GOLDEN_APPLE || this == CARROTS || this == POTATOES || this == BEETROOT_SEEDS || this == SWEET_BERRY_BUSH; }
    public int getMaxDurability() { return item() == null ? 0 : item().getDefaultInstance().getMaxDamage(); }
    public float getHardness() {
        if (!isBlock()) return 0.0f;
        var block = BuiltInRegistries.BLOCK.getOptional(ResourceLocation.withDefaultNamespace(name().toLowerCase(java.util.Locale.ROOT))).orElse(Blocks.AIR);
        return block.defaultBlockState().getDestroySpeed(null, net.minecraft.core.BlockPos.ZERO);
    }
    public Item item() { return BuiltInRegistries.ITEM.getOptional(ResourceLocation.withDefaultNamespace(name().toLowerCase(java.util.Locale.ROOT))).orElse(null); }
    public ItemStack itemStack() { Item item = item(); return item == null ? ItemStack.EMPTY : new ItemStack(item); }
    public Object createBlockData() { return this; }
    public static Material fromNms(net.minecraft.world.item.ItemStack stack) { if (stack == null || stack.isEmpty()) return AIR; String id=BuiltInRegistries.ITEM.getKey(stack.getItem()).getPath().toUpperCase(java.util.Locale.ROOT); try{return valueOf(id);}catch(Exception e){return AIR;} }
    public boolean isLegacy(){return false;}
}
